// app/utils/arenaMap.ts
// Mapeia índice de arena (0–25) → PNG local
export const arenaMap: Record<number, any> = {
  0: require('../../assets/arena/arena0.png'),
  1: require('../../assets/arena/arena1.png'),
  2: require('../../assets/arena/arena2.png'),
  3: require('../../assets/arena/arena3.png'),
  4: require('../../assets/arena/arena4.png'),
  5: require('../../assets/arena/arena5.png'),
  6: require('../../assets/arena/arena6.png'),
  7: require('../../assets/arena/arena7.png'),
  8: require('../../assets/arena/arena8.png'),
  9: require('../../assets/arena/arena9.png'),
  10: require('../../assets/arena/arena10.png'),
  11: require('../../assets/arena/arena11.png'),
  12: require('../../assets/arena/arena12.png'),
  13: require('../../assets/arena/arena13.png'),
  14: require('../../assets/arena/arena14.png'),
  15: require('../../assets/arena/arena15.png'),
  16: require('../../assets/arena/arena16.png'),
  17: require('../../assets/arena/arena17.png'),
  18: require('../../assets/arena/arena18.png'),
  19: require('../../assets/arena/arena19.png'),
  20: require('../../assets/arena/arena20.png'),
  21: require('../../assets/arena/arena21.png'),
  22: require('../../assets/arena/arena22.png'),
  23: require('../../assets/arena/arena23.png'),
  24: require('../../assets/arena/arena24.png'),
};
